---

- name: Start postfix
  ansible.builtin.service:
    name: postfix
    state: "started"

- name: Postmap smarthost_passwd
  ansible.builtin.command: "postmap /etc/postfix/smarthost_passwd"
  args:
    chdir: "/etc/postfix"
  when: smarthost is success

- name: Restart postfix
  ansible.builtin.service:
    name: "postfix"
    state: "restarted"
  when: >
    not (
      ansible_os_family == "RedHat" and ansible_virtualization_type is defined and (
        ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd"
      )
    )

- name: Makemap secrets
  ansible.builtin.command: makemap /etc/mail/secrets

- name: Restart opensmtpd
  ansible.builtin.command: rcctl restart smtpd
