---

- name: Verify
  hosts: smarthost
  pre_tasks:
    - name: RedHat | Ensure pgrep is present
      ansible.builtin.package:
        name: procps-ng
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int >= 8
  tasks:

    - name: Ensure process is running
      ansible.builtin.command: pgrep -u root master
      register: ps
      changed_when: false
      ignore_errors: true
    - name: Validate ps output
      ansible.builtin.assert:
        that: ps.stdout
      when: >
        not (
          ansible_os_family == "RedHat" and ansible_virtualization_type is defined and (
            ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd"
          )
        )

    - name: Fetch content of /etc/postfix/smarthost_passwd
      ansible.builtin.slurp:
        src: /etc/postfix/smarthost_passwd
      register: passfile
    - name: Validate /etc/postfix/smarthost_passwd
      ansible.builtin.assert:
        that: >
                "'login:pass' in passfile['content'] | b64decode"

    - name: Fetch content of /etc/postfix/main.cf
      ansible.builtin.slurp:
        src: /etc/postfix/main.cf
      register: cfg
    - name: Validate /etc/postfix/main.cf
      ansible.builtin.assert:
        that: >
                "'relayhost = [smtp.gmail.com]:587' in cfg['content'] | b64decode"
